---
job: extension
config:
  name: "envisage_kontext_rhinoplasty_v1"
  process:
    - type: 'sd_trainer'
      training_folder: "./checkpoints/kontext"
      device: cuda:0
      trigger_word: "envisage_rhino"
      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
      save:
        dtype: float16
        save_every: 100
        max_step_saves_to_keep: 5
        push_to_hub: false
      datasets:
        - folder_path: "./data/training/kontext/rhinoplasty/target"
          control_path: "./data/training/kontext/rhinoplasty/control"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [ 512 ]
      train:
        batch_size: 1
        steps: 1000
        gradient_accumulation_steps: 2
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        lr: 1e-4
        timestep_type: "weighted"
        dtype: bf16
      model:
        name_or_path: "black-forest-labs/FLUX.1-Kontext-dev"
        arch: "flux_kontext"
        quantize: false
      sample:
        sampler: "flowmatch"
        sample_every: 100
        width: 512
        height: 512
        prompts:
          - "envisage_rhino style, refined thin nose with straight bridge and defined tip, same person  --ctrl_img ./data/training/kontext/rhinoplasty/control/Nose_01.png"
          - "envisage_rhino style, refined thin nose with straight bridge and defined tip, same person  --ctrl_img ./data/training/kontext/rhinoplasty/control/Nose_05.png"
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20
meta:
  name: "[name]"
  version: '1.0'
