"""Surgical mask generator with feathering.

Creates procedure-specific inpainting masks from MediaPipe landmarks.
Masks define the region to be regenerated by the diffusion model.

Supported procedures:
  - rhinoplasty: nose dorsum + tip + wings
  - blepharoplasty: upper/lower eyelids
  - orthognathic: jaw contour + chin

Each mask is:
  1. Convex hull of procedure-specific landmarks
  2. Dilated by a configurable margin (default 20px)
  3. Gaussian-feathered for smooth blending (default sigma=12)
  4. Padded to dimensions divisible by 16 (diffusion model requirement)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

from .landmarks import (
    FaceLandmarks,
    get_region_points,
    measure_eyelid_hooding,
    measure_jaw,
    LEFT_EYE_UPPER,
    LEFT_EYE_LOWER,
    RIGHT_EYE_UPPER,
    RIGHT_EYE_LOWER,
    LEFT_UPPER_LID_FOLD,
    RIGHT_UPPER_LID_FOLD,
    JAW_CONTOUR,
    LOWER_JAW,
)

log = logging.getLogger(__name__)


@dataclass
class MaskConfig:
    """Configuration for mask generation."""

    dilation_px: int = 20
    feather_sigma: float = 12.0
    pad_to_multiple: int = 16
    min_mask_area: int = 100  # minimum mask area in pixels


def active_bleph_mask_config() -> MaskConfig:
    """Live bleph geometry used on the guarded pipeline and smoke paths."""
    return MaskConfig(dilation_px=10, feather_sigma=5.0)


def active_rhyt_mask_config() -> MaskConfig:
    """Live rhyt geometry used on the guarded pipeline and smoke paths."""
    return MaskConfig(dilation_px=8, feather_sigma=5.0)


def generate_mask(
    landmarks: FaceLandmarks,
    procedure: str,
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Generate a feathered surgical mask from landmarks.

    Args:
        landmarks: Extracted face landmarks.
        procedure: Surgical procedure name.
        config: Mask generation parameters.

    Returns:
        (H, W) float32 mask in [0, 1] range, feathered at edges.
    """
    if config is None:
        config = MaskConfig()

    w, h = landmarks.image_size
    region_pts = get_region_points(landmarks, procedure)

    if len(region_pts) < 3:
        log.warning(
            "Too few landmarks (%d) for %s mask, using elliptical fallback",
            len(region_pts),
            procedure,
        )
        return _fallback_mask(w, h, procedure, config)

    # Binary mask from convex hull
    mask = np.zeros((h, w), dtype=np.uint8)
    hull = cv2.convexHull(region_pts.astype(np.int32))
    cv2.fillConvexPoly(mask, hull, 255)

    # Check minimum area
    if cv2.countNonZero(mask) < config.min_mask_area:
        log.warning("Mask area too small for %s, using elliptical fallback", procedure)
        return _fallback_mask(w, h, procedure, config)

    # Dilate to include surrounding tissue
    if config.dilation_px > 0:
        ksize = 2 * config.dilation_px + 1
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
        mask = cv2.dilate(mask, kernel, iterations=1)

    # Gaussian feathering for smooth blending
    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(
            mask, (0, 0), sigmaX=config.feather_sigma
        )

    # Normalize to [0, 1]
    mask_f = mask.astype(np.float32) / 255.0

    # Pad to multiple of pad_to_multiple
    mask_f = _pad_to_multiple(mask_f, config.pad_to_multiple)

    log.info(
        "Generated %s mask: %dx%d, coverage=%.1f%%",
        procedure,
        mask_f.shape[1],
        mask_f.shape[0],
        100.0 * (mask_f > 0.5).sum() / mask_f.size,
    )
    return mask_f


def generate_combined_mask(
    landmarks: FaceLandmarks,
    procedures: list[str],
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Generate a combined mask for multiple procedures.

    Useful for combined surgeries (e.g., rhinoplasty + genioplasty).

    Args:
        landmarks: Extracted face landmarks.
        procedures: List of procedure names.
        config: Mask generation parameters.

    Returns:
        (H, W) float32 combined mask in [0, 1].
    """
    if not procedures:
        raise ValueError("At least one procedure required")

    combined = None
    for proc in procedures:
        mask = generate_mask(landmarks, proc, config)
        if combined is None:
            combined = mask.copy()
        else:
            # Resize if needed (different procedures might produce different padding)
            if combined.shape != mask.shape:
                mask = cv2.resize(mask, (combined.shape[1], combined.shape[0]))
            combined = np.maximum(combined, mask)

    return combined


def generate_adaptive_bleph_mask(
    landmarks: FaceLandmarks,
    config: MaskConfig | None = None,
    intensity_pct: float = 50.0,
) -> np.ndarray:
    """Generate adaptive blepharoplasty mask with per-eye dilation.

    The more hooded eye gets more dilation so both eyes end up with
    approximately equal mask coverage.

    Args:
        landmarks: Face landmarks.
        config: Base mask config.
        intensity_pct: 0-100 intensity slider value.

    Returns:
        (H, W) float32 mask in [0, 1].
    """
    if config is None:
        config = active_bleph_mask_config()

    w, h = landmarks.image_size
    hooding = measure_eyelid_hooding(landmarks)

    # Base dilation proportional to crease-to-brow distance
    left_base = hooding["left_crease_to_brow"]
    right_base = hooding["right_crease_to_brow"]

    # More hooded eye (lower hooding ratio) gets more dilation
    left_hood = hooding["left_hooding"]
    right_hood = hooding["right_hooding"]
    max_hood = max(left_hood, right_hood, 0.1)

    # Scale: invert hooding so the MORE hooded eye gets larger dilation
    left_dilation = int(config.dilation_px * (max_hood / max(left_hood, 0.1)))
    right_dilation = int(config.dilation_px * (max_hood / max(right_hood, 0.1)))

    # Clamp to reasonable range
    left_dilation = max(5, min(left_dilation, config.dilation_px * 3))
    right_dilation = max(5, min(right_dilation, config.dilation_px * 3))

    mask = np.zeros((h, w), dtype=np.uint8)

    pts = landmarks.points

    # Left eye: mask the skin fold ABOVE the lash line only
    left_pts = pts[[i for i in LEFT_UPPER_LID_FOLD if i < len(pts)]]
    if len(left_pts) >= 3:
        hull = cv2.convexHull(left_pts.astype(np.int32))
        left_mask = np.zeros((h, w), dtype=np.uint8)
        cv2.fillConvexPoly(left_mask, hull, 255)
        if left_dilation > 0:
            ksize = 2 * left_dilation + 1
            kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
            left_mask = cv2.dilate(left_mask, kernel, iterations=1)
        mask = np.maximum(mask, left_mask)

    # Right eye: same
    right_pts = pts[[i for i in RIGHT_UPPER_LID_FOLD if i < len(pts)]]
    if len(right_pts) >= 3:
        hull = cv2.convexHull(right_pts.astype(np.int32))
        right_mask = np.zeros((h, w), dtype=np.uint8)
        cv2.fillConvexPoly(right_mask, hull, 255)
        if right_dilation > 0:
            ksize = 2 * right_dilation + 1
            kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
            right_mask = cv2.dilate(right_mask, kernel, iterations=1)
        mask = np.maximum(mask, right_mask)

    # CRITICAL: Exclude the eye opening (iris, pupil, lashes)
    # Cut out the area below the upper lid margin
    for eye_upper, eye_lower in [(LEFT_EYE_UPPER, LEFT_EYE_LOWER),
                                  (RIGHT_EYE_UPPER, RIGHT_EYE_LOWER)]:
        upper_pts = pts[[i for i in eye_upper if i < len(pts)]].astype(np.int32)
        lower_pts = pts[[i for i in eye_lower if i < len(pts)]].astype(np.int32)
        if len(upper_pts) >= 3 and len(lower_pts) >= 3:
            # Build polygon of the eye opening and cut it out
            eye_poly = np.vstack([upper_pts, lower_pts[::-1]])
            eye_opening = np.zeros((h, w), dtype=np.uint8)
            cv2.fillPoly(eye_opening, [eye_poly], 255)
            # Dilate the eye opening cutout by 5px to protect lashes
            eye_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (11, 11))
            eye_opening = cv2.dilate(eye_opening, eye_kernel)
            # Subtract from mask
            mask = cv2.subtract(mask, eye_opening)

    # Feather
    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(mask, (0, 0), sigmaX=config.feather_sigma)

    mask_f = mask.astype(np.float32) / 255.0

    # Inpainting strength scaling
    strength = 0.3 + 0.25 * (intensity_pct / 100.0)

    log.info(
        "Adaptive bleph mask: L_dil=%d R_dil=%d L_hood=%.2f R_hood=%.2f strength=%.2f",
        left_dilation, right_dilation, left_hood, right_hood, strength,
    )
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


# ---------------------------------------------------------------------------
# Preset-aware blepharoplasty mask (upper + lower + lateral families)
# ---------------------------------------------------------------------------

_UPPER_BLEPH_PRESETS = frozenset({
    "upper_skin_excision", "crease_restoration", "upper_dehooding",
    "lid_symmetry", "fat_pad_reduction",
})
_LOWER_BLEPH_PRESETS = frozenset({"lower_bag_reduction", "tear_trough_smoothing"})
_LATERAL_BLEPH_PRESETS = frozenset({"crow_feet_softening"})


def _add_upper_lid_region(
    mask: np.ndarray,
    pts: np.ndarray,
    config: MaskConfig,
) -> None:
    """Add upper-lid fold region to the mask in-place."""
    for fold_idx in (LEFT_UPPER_LID_FOLD, RIGHT_UPPER_LID_FOLD):
        lid_pts = pts[[i for i in fold_idx if i < len(pts)]]
        if len(lid_pts) < 3:
            continue
        hull = cv2.convexHull(lid_pts.astype(np.int32))
        sub = np.zeros_like(mask)
        cv2.fillConvexPoly(sub, hull, 255)
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,
                                           (config.dilation_px, config.dilation_px))
        sub = cv2.dilate(sub, kernel, iterations=1)
        mask[:] = np.maximum(mask, sub)


def _add_lower_lid_region(
    mask: np.ndarray,
    pts: np.ndarray,
    include_tear_trough: bool,
) -> None:
    """Add lower-lid bag region to the mask. Extends downward from the
    lower lash line. If include_tear_trough, extends medially toward the
    nasojugal groove.
    """
    for lower_idx in (LEFT_EYE_LOWER, RIGHT_EYE_LOWER):
        lid_pts = pts[[i for i in lower_idx if i < len(pts)]].astype(np.int32)
        if len(lid_pts) < 3:
            continue
        # Eye height as proxy for bag extent
        ymin = lid_pts[:, 1].min()
        ymax = lid_pts[:, 1].max()
        eye_h = max(ymax - ymin, 10)
        bag_extent = int(eye_h * 3.0)  # extend ~3x eye height downward

        # Build a polygon: lower lid margin + extended points below it
        margin_top = lid_pts.copy()
        margin_bottom = lid_pts.copy()
        margin_bottom[:, 1] += bag_extent
        # Optionally extend medially for tear trough
        if include_tear_trough:
            inner_idx = 0  # MediaPipe inner canthus is first in LEFT_EYE_LOWER
            margin_bottom[inner_idx, 0] -= int(eye_h * 0.8)  # move medial
            margin_bottom[inner_idx, 1] += int(eye_h * 0.5)

        poly = np.concatenate([margin_top, margin_bottom[::-1]], axis=0)
        sub = np.zeros_like(mask)
        cv2.fillPoly(sub, [poly], 255)
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
        sub = cv2.dilate(sub, kernel, iterations=1)
        mask[:] = np.maximum(mask, sub)


def _add_lateral_periorbital_region(
    mask: np.ndarray,
    pts: np.ndarray,
) -> None:
    """Small lateral patches outside each outer canthus for crow's feet."""
    # Outer canthi: 33 (left), 263 (right) in MediaPipe
    for canthus_idx in (33, 263):
        if canthus_idx >= len(pts):
            continue
        cx, cy = int(pts[canthus_idx][0]), int(pts[canthus_idx][1])
        direction = +1 if canthus_idx == 33 else -1
        # Small ellipse lateral to the canthus
        center = (cx - 15 * direction, cy)
        axes = (22, 14)
        sub = np.zeros_like(mask)
        cv2.ellipse(sub, center, axes, 0, 0, 360, 255, -1)
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (10, 10))
        sub = cv2.dilate(sub, kernel, iterations=1)
        mask[:] = np.maximum(mask, sub)


def _cut_out_eye_openings(
    mask: np.ndarray,
    pts: np.ndarray,
    dilate_px: int = 7,
) -> None:
    """Subtract the iris/sclera/lash region so diffusion can't touch them."""
    for upper_idx, lower_idx in (
        (LEFT_EYE_UPPER, LEFT_EYE_LOWER),
        (RIGHT_EYE_UPPER, RIGHT_EYE_LOWER),
    ):
        upper = pts[[i for i in upper_idx if i < len(pts)]].astype(np.int32)
        lower = pts[[i for i in lower_idx if i < len(pts)]].astype(np.int32)
        if len(upper) < 3 or len(lower) < 3:
            continue
        eye_poly = np.vstack([upper, lower[::-1]])
        cutout = np.zeros_like(mask)
        cv2.fillPoly(cutout, [eye_poly], 255)
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,
                                           (dilate_px * 2 + 1, dilate_px * 2 + 1))
        cutout = cv2.dilate(cutout, kernel)
        mask[:] = cv2.subtract(mask, cutout)


def generate_preset_aware_bleph_mask(
    landmarks: FaceLandmarks,
    active_keys: set[str] | list[str],
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Build a blepharoplasty mask based on which presets are active.

    - Upper-family presets → upper-lid fold mask.
    - Lower-family presets (bag, tear trough) → lower-lid region below the
      lash line, extended down ~3x eye height. Tear trough also extends
      medially toward the nasojugal groove.
    - Lateral presets (crow's feet) → small ellipses outside each outer
      canthus.
    - Always subtracts the eye-opening (iris/sclera/lashes) with a 7px
      safety margin so diffusion cannot overwrite those regions.

    Returns a float32 mask in [0, 1], padded to `config.pad_to_multiple`.
    """
    if config is None:
        config = MaskConfig(dilation_px=20, feather_sigma=12)

    active = set(active_keys or [])
    h, w = landmarks.image_size[1], landmarks.image_size[0]
    mask = np.zeros((h, w), dtype=np.uint8)
    pts = landmarks.points

    has_upper = bool(active & _UPPER_BLEPH_PRESETS)
    has_lower = bool(active & _LOWER_BLEPH_PRESETS)
    has_lateral = bool(active & _LATERAL_BLEPH_PRESETS)

    # Safe default: if nothing flagged, target upper lid so the pipeline
    # does the most common bleph by default.
    if not (has_upper or has_lower or has_lateral):
        has_upper = True

    if has_upper:
        _add_upper_lid_region(mask, pts, config)
    if has_lower:
        _add_lower_lid_region(mask, pts, include_tear_trough="tear_trough_smoothing" in active)
    if has_lateral:
        _add_lateral_periorbital_region(mask, pts)

    # Always protect the eye openings themselves
    _cut_out_eye_openings(mask, pts, dilate_px=7)

    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(mask, (0, 0), sigmaX=config.feather_sigma)

    mask_f = mask.astype(np.float32) / 255.0

    log.info(
        "Preset-aware bleph mask: upper=%s lower=%s lateral=%s (active=%s)",
        has_upper, has_lower, has_lateral, sorted(active),
    )
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


def generate_adaptive_rhytid_mask(
    landmarks: FaceLandmarks,
    config: MaskConfig | None = None,
    *,
    include_neck: bool = False,
) -> np.ndarray:
    """Generate adaptive rhytidectomy mask following the jaw contour.

    The mask follows the actual jaw contour (not a horizontal line),
    with a 5px feather along the contour. The neck region extends to
    the bottom of the image.

    Args:
        landmarks: Face landmarks.
        config: Base mask config.
        include_neck: When False, restrict the mask to a jawline band even if
            the image includes visible neck below the chin.

    Returns:
        (H, W) float32 mask in [0, 1].
    """
    if config is None:
        config = active_rhyt_mask_config()

    w, h = landmarks.image_size
    pts = landmarks.points
    jaw = measure_jaw(landmarks)

    mask = np.zeros((h, w), dtype=np.uint8)

    # Use LOWER_JAW only; NO temples/forehead/cheeks
    jaw_indices = [i for i in LOWER_JAW if i < len(pts)]
    if len(jaw_indices) < 5:
        return _fallback_mask(w, h, "rhytidectomy", config)

    jaw_pts = pts[jaw_indices].astype(np.int32)

    # Sort jaw points left-to-right for a clean contour
    sorted_jaw = jaw_pts[jaw_pts[:, 0].argsort()]

    # Create polygon: jaw contour + image bottom corners
    contour = list(sorted_jaw)
    # Extend to image edges at bottom
    contour.append([w - 1, h - 1])
    contour.append([0, h - 1])
    contour = np.array(contour, dtype=np.int32)

    # Fill below-jaw region (neck + jawline)
    cv2.fillPoly(mask, [contour], 255)

    # Check if image includes significant neck area
    chin_y = jaw["chin_y"]
    neck_extent = h - chin_y
    has_neck = neck_extent > h * 0.1  # at least 10% of image below chin

    if not include_neck or not has_neck:
        # Image cropped at chin, only do jawline, skip neck
        # Restrict mask to a band around the jaw contour
        jaw_band = np.zeros((h, w), dtype=np.uint8)
        for i in range(len(sorted_jaw) - 1):
            cv2.line(jaw_band, tuple(sorted_jaw[i]), tuple(sorted_jaw[i + 1]), 255, 20)
        mask = cv2.bitwise_and(mask, jaw_band)
        reason = "jaw-only override" if include_neck is False else "chin-cropped image"
        log.info("Rhytid mask: %s, jawline only", reason)

    # Feather along jaw contour (5px)
    feather_mask = np.zeros((h, w), dtype=np.uint8)
    for i in range(len(sorted_jaw) - 1):
        cv2.line(feather_mask, tuple(sorted_jaw[i]), tuple(sorted_jaw[i + 1]), 255, 10)
    feather_mask = cv2.GaussianBlur(feather_mask, (0, 0), sigmaX=5)

    # Combine: hard mask below jaw, feathered at contour
    mask_f = mask.astype(np.float32) / 255.0
    feather_f = feather_mask.astype(np.float32) / 255.0

    # The upper boundary of the mask gets the feather treatment
    mask_f = np.maximum(mask_f, feather_f * 0.5)

    if config.feather_sigma > 0:
        mask_f = cv2.GaussianBlur(mask_f, (0, 0), sigmaX=config.feather_sigma / 2)

    log.info(
        "Adaptive rhytid mask: jaw_w=%.0f chin_y=%.0f has_neck=%s include_neck=%s",
        jaw["jaw_width"], chin_y, has_neck, include_neck,
    )
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


def mask_to_pil(mask: np.ndarray) -> Image.Image:
    """Convert float32 mask [0,1] to PIL Image (L mode, [0,255])."""
    return Image.fromarray((mask * 255).astype(np.uint8), mode="L")


def save_mask(mask: np.ndarray, path: str | Path) -> None:
    """Save mask as PNG."""
    mask_to_pil(mask).save(str(path))
    log.info("Saved mask to %s", path)


def _fallback_mask(
    w: int,
    h: int,
    procedure: str,
    config: MaskConfig,
) -> np.ndarray:
    """Generate a heuristic elliptical mask when landmarks are insufficient."""
    mask = np.zeros((h, w), dtype=np.uint8)

    # Approximate mask centers relative to image dimensions
    params = {
        "rhinoplasty": (0.50, 0.55, 0.12, 0.15),
        "blepharoplasty": (0.50, 0.38, 0.25, 0.06),
        "orthognathic": (0.50, 0.72, 0.20, 0.18),
        "rhytidectomy": (0.50, 0.60, 0.35, 0.30),
    }
    cx_r, cy_r, rx_r, ry_r = params.get(procedure, (0.50, 0.50, 0.15, 0.15))

    cx, cy = int(w * cx_r), int(h * cy_r)
    rx, ry = int(w * rx_r), int(h * ry_r)
    cv2.ellipse(mask, (cx, cy), (rx, ry), 0, 0, 360, 255, -1)

    if config.dilation_px > 0:
        ksize = 2 * config.dilation_px + 1
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
        mask = cv2.dilate(mask, kernel, iterations=1)

    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(mask, (0, 0), sigmaX=config.feather_sigma)

    mask_f = mask.astype(np.float32) / 255.0
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


def _pad_to_multiple(mask: np.ndarray, multiple: int) -> np.ndarray:
    """Pad mask so dimensions are divisible by `multiple`."""
    h, w = mask.shape[:2]
    new_h = ((h + multiple - 1) // multiple) * multiple
    new_w = ((w + multiple - 1) // multiple) * multiple
    if new_h == h and new_w == w:
        return mask
    padded = np.zeros((new_h, new_w), dtype=mask.dtype)
    padded[:h, :w] = mask
    return padded
